[config]


[env]
RELEASE = { source = "${CARGO_MAKE_PROFILE}", default_value = "false", mapping = {release = "true"} }
RELEASE_FLAG = { source = "${CARGO_MAKE_PROFILE}", default_value = "", mapping = {release = "--release"} }
PROFILE_FOLDER = { source = "${CARGO_MAKE_PROFILE}", default_value = "debug", mapping = {release = "release"} }
KERNEL_ELF = "target/riscv64gc-unknown-none-elf/${PROFILE_FOLDER}/breakcore-os"
KERNEL_BIN = "${KERNEL_ELF}.bin"
KERNEL_DEBUGINFO = "${KERNEL_ELF}.debuginfo"
USER_PROGRAMS = "exec_test hello_world"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.default]
workspace = false
alias = "empty"

[tasks.install-rustsbi]
workspace = false
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/bootloader/rustsbi-qemu.bin"] }
install_script = '''
mkdir -p bootloader
echo Installing RustSBI...
curl -L https://github.com/rcore-os/rCore-Tutorial-v3/raw/dev/bootloader/rustsbi-qemu.bin --output bootloader/rustsbi-qemu.bin
'''

[tasks.just-run]
workspace = false
script = '''
echo ${KERNEL_BIN}
qemu-system-riscv64 \
	-machine virt \
	-m 128M \
	-nographic \
	-bios bootloader/rustsbi-qemu.bin \
	-device loader,file=${KERNEL_BIN},addr=0x80020000 \
	-device loader,file=${KERNEL_DEBUGINFO},addr=0x80800000,force-raw=on
'''
dependencies = ["install-rustsbi"]

[tasks.run]
workspace = false
run_task = "just-run"
dependencies = ["install-rustsbi","kernel"]

[tasks.kernel]
workspace = false
script = '''
rust-objcopy --binary-architecture=riscv64  \
	${KERNEL_ELF} \
	--strip-all -O binary \
	${KERNEL_BIN}
rust-objcopy --binary-architecture=riscv64  \
	${KERNEL_ELF} \
	--only-keep-debug \
	${KERNEL_DEBUGINFO}
echo ${KERNEL_ELF} "->" ${KERNEL_BIN} ${KERNEL_DEBUGINFO}
'''
dependencies = ["user","build-kernel"]


[tasks.user]
workspace = false
script = '''
names="${USER_PROGRAMS}"
for name in $names
do
	# name=$(echo $f|sed 's/^user\/src\/bin\///;s/\.rs$//')
	elf="target/riscv64gc-unknown-none-elf/${PROFILE_FOLDER}/$name"
	dest_elf="target/riscv64gc-unknown-none-elf/$name"
	echo $elf "->" $dest_elf
	cp $elf $dest_elf
done
'''
dependencies = ["build-user"]

[tasks.build-kernel]
workspace = false
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["os"] }
run_task = "build-crate"
dependencies = ["user"]


[tasks.build-user]
workspace = false
script_runner = "@duckscript"
script = '''
names = split ${USER_PROGRAMS} " "
bins_tail = array_join ${names} " --bin "
bins = concat "--bin " ${bins_tail}
echo ${bins}
set_env USER_BINARY "${bins}"
cm_run_task build-user-bin
'''

[tasks.build-crate]
workspace = false
run_task = [
	{ name = "build", fork = true, condition = { env_false = ["RELEASE"] } },
	{ name = "build-release", fork = true, condition = { env_true = ["RELEASE"] } }
]

[tasks.build-user-bin]
workspace = false
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["user"] }
run_task = [
	{ name = "build-user-bin-inner", fork = true },
]

[tasks.build-user-bin-inner]
command = "cargo"
args = [
	"build",
	"@@remove-empty(RELEASE_FLAG)",
	"@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
	"@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
	"@@split(USER_BINARY, )"
]

[tasks.objdump]
workspace = false
script = '''
rust-objdump --arch-name=riscv64 -x --disassemble  \
	${KERNEL_ELF}  | less
'''

[tasks.clean]
workspace = false